# Generated by Django 4.2.5 on 2023-09-30 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audios/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])]),
        ),
        migrations.AddField(
            model_name='videochunk',
            name='audio_chunk_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_chunks/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])]),
        ),
    ]
