# Generated by Django 4.2.5 on 2023-09-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_remove_video_video_video_video_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_base64',
            field=models.TextField(),
        ),
    ]
