# Generated by Django 4.2.5 on 2023-09-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_video_video_base64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_base64',
        ),
        migrations.AddField(
            model_name='video',
            name='video_binary',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
